# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=500)),
                ('authorCode', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ItemContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('itemCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NavItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=500)),
                ('itemCode', models.CharField(max_length=500)),
                ('navCode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navName', models.CharField(max_length=500)),
                ('navCode', models.CharField(max_length=500)),
                ('authorCode', models.CharField(max_length=500)),
            ],
        ),
    ]
